spring:
  application:
    name: movie-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath:/movie-service.sql

server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false